
spring:
  output:
    ansi:
      enabled:
        always


  application:
    name:
      cart-service

  jpa:
    showSql:
      true

    hibernate:
      ddlAuto:
        update

  h2:
    console:
      enabled:
        true

  jackson:
    serializaton:
      FAIL_ON_EMPTY_BEANS:
        false

logging:
  level:
    org:
      hibernate:
        SQL:
          DEBUG

        type:
          TRACE


eureka:
  client:
    serviceUrl:
      defaultZone:
        http://localhost:8761/eureka

server:
  port:
    8084


